### ISSUE TITLE
Bump PNG16 Version to 1.6.34

### ISSUE THREAD

**Issue by VisualFox** [lovell/sharp-libvips#1]
Issue:
When building on linux https://ftp-osl.osuosl.org/pub/libpng/src/libpng16/libpng-1.6.32.tar.xz return a 404

Fix:
in build/lin.sh version_png16 need to be bump up to 1.6.34
VERSION_PNG16=1.6.34

That seem a bit silly to create a PR just for that, but I can do it if that makes your life easier :)

**Comment by lovell** [comment]
There's a fairly big update to the Linux build script coming shortly, ahead of sharp v0.19.0, which will include this update. Thanks for the offer.

**Comment by VisualFox** [comment]
That good to hear. Thank you for all your hard work!

BTW: I also got some issue with the libvips archive when targeting 8.5.9 - I think the current url in lin.sh is hardcoded for the upcoming 8.6.0

**Comment by lovell** [comment]
Commit f39f780 bumps the libpng version (amongst others) and provides a latest version checking feature. There'll be another update when libvips v8.6.0 is released.
