### ISSUE TITLE
borked on smartos (and I would guess other *solaris)

### ISSUE THREAD

**Issue by gotwf** [lovell/sharp-libvips#12]
Be nice if a sharp binary existed for smartos but since such apparently does not npm tries to build it.  Which doesn't work out too well since libvips-8.7.0-sunos-x64.tar.gz is not in the lurking:

[admin@samhain ~]$ npm i sharp

> sharp@0.21.0 install /home/admin/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-sunos-x64.tar.gz
/home/admin/node_modules/sharp/install/libvips.js:80
          throw new Error(`Status ${response.statusCode}`);
          ^

Error: Status 404

In any case, thought I'd let ya' know in case ya' wanted to shave yer' script!

fwiw:

[admin@samhain ~]$ uname -a  
SunOS samhain 5.11 joyent_20180816T001857Z i86pc i386 i86pc

Otherwise know as a Joyent minimal 64 bit 18.3 smartos vm.

**Comment by lovell** [comment]
Hello, for SmartOS/SunOS you'll need to globally install libvips from source first.

http://sharp.pixelplumbing.com/en/stable/install/#building-from-source

 `sharp` will always look for `libvips` before attempting to download prebuilt binaries, although we should probably skip trying when `os.platform()` reports `sunos`.

**Comment by gotwf** [comment]
Yes.  I was aware of that.  pkgsrc does not have a libvips pkg and I have not been able to get it to build myself as of yet either.

Probably just disregard this cuz it's more upstream issue.  Thx.

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/473afaab450ecba6fb5d901868a5936c7801f39e improves the error messaging for SunOS users that have not yet globally-installed libvips. Thanks for reporting.
