### ISSUE TITLE
Libvips installation problem

### ISSUE THREAD

**Issue by cemiltokatli** [lovell/sharp-libvips#14]
I am trying to install sharp via NPM on my CentOS 7 and getting the error below:

`sharp@0.20.8 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`

I guess I need to install libvips. According to a post on Sharp's issue page, I need a libvips package equal to or more than 8.4.2. I have just downloaded "libvips-8.7.0-linux-x64.tar.gz" package to my server but have no idea how can I make it work. There are a bunch of *.so files. I added the path to environment variables but still not working.

The full error that I've been getting during the sharp installation is:

```npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! sharp@0.20.8 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sharp@0.20.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-27T22_52_35_599Z-debug.log```

**Comment by lovell** [comment]
Hello, it looks like you're running `npm install` as the root user; I strongly advise you to use a non-root user.

If you absolutely have to use root, ensure npm's [unsafe-perm](https://docs.npmjs.com/misc/config#unsafe-perm) flag is set e.g. `npm install --unsafe-perm`.

**Comment by bencmbrook** [comment]
I'm having the same install bug:

**Comment by bencmbrook** [comment]
Bizarre. By deleting `/Users/bencmbrook/.npm/_libvips/libvips-8.7.0-darwin-x64.tar.gz` and re-running the `npm install` it now works. Something must have gone wrong (but without error) on with the first download

>info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-darwin-x64.tar.gz

**Comment by lovell** [comment]
@bencmbrook Thanks to your report I spotted a missing error handler, now added in commit https://github.com/lovell/sharp/commit/a2aa7d69e7eb1ce5c154480130fef0977356612a

@cemiltokatli Hope my original answer helped you, please feel free to reopen if not.

**Comment by flq** [comment]
Incredible find @bencmbrook this was exactly my error, too - on OSX I had to install XCode for reasons, and these errors may have left the file corrupted? But really, I'm just guessing here...

**Comment by GuidovdRiet** [comment]
Receiving the samen error:

```
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/compname/.npm/_libvips/libvips-8.7.0-darwin-x64.tar.gz
ERR! sharp zlib: Cannot read property 'length' of null
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
```

Even after deleting `libvips-8.7.0-darwin-x64.tar.gz` 

What could be the problem here?
