### ISSUE TITLE
Consider re-releasing artifacts

### ISSUE THREAD

**Issue by lucasff** [lovell/sharp-libvips#141]
Hello!

I have a use case that I'm using Apple silicon, but with an older project, that uses `v8.10.0`.
Would be possible to automatically add artifacts for older releases that contain prebuilt binaries?
In the end, it will avoid:
`ERR! sharp Prebuilt libvips 8.10.0 binaries are not yet available for linuxmusl-arm64v8`
and the need to compile (time) and configure the environment to have the deps.

Thank you!

**Comment by lovell** [comment]
No, sorry, please upgrade.
