### ISSUE TITLE
Compile Linux x64 binaries with `-march=x86-64-v2`?

### ISSUE THREAD

**Issue by kleisauke** [lovell/sharp-libvips#153]
Instead of compiling the Linux x64 binaries with [ `-march=westmere`](https://github.com/lovell/sharp-libvips/blob/a40f861fae54f23d8ea396a483a2d2b93288fc91/linux-x64/Dockerfile#L39) perhaps we should lower it to `-march=x86-64-v2`? This would allow the binaries to run on Intel Nehalem, which doesn't support the AES and PCLMUL instruction sets.

Context: https://github.com/kleisauke/net-vips/issues/176.

**Comment by lovell** [comment]
Oh, I hadn't seen this. The introduction of numeric levels for x64 microarchitecture is a great idea that helps deal with the proliferation of intrinsics. I agree we should align, and v2 makes sense.

We should also add `-mtune=nehalem` as `-march=x86-64-v2` appears not to automagically select it.

I guess it's possible that the removal of PCLMUL might affect `zlib-ng` performance, but that's a guess.
