### ISSUE TITLE
Why does this use libjpeg-turbo when mozjpeg is better at compression?

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp-libvips#17]
https://github.com/lovell/sharp-libvips/blob/master/build/lin.sh#L154

**Comment by lovell** [comment]
The binaries created by this script are provided to help most people most of the time.

sharp will always look for a globally-installed libvips before using these binaries so you can compile libvips from source with whichever dependencies you need.

**Comment by adityapatadia** [comment]
What is best way according to you? Any disadvantages of using mozjpeg?

**Comment by lovell** [comment]
https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball

**Comment by adityapatadia** [comment]
Thanks for pointing out the documentation. I have good experience with building vips. I just want to know if I will get more advantages / disadvantages if I build with mozjpeg. Does it decrease encoding speed significantly?

**Comment by lovell** [comment]
It depends ;) I recommend trying it on your workload to see if the performance trade-offs are worth it.
