### ISSUE TITLE
linuxmusl-armv6 and linuxmusl-armv7 prebuilds?

### ISSUE THREAD

**Issue by Rubber1Duck** [lovell/sharp-libvips#175]
is it possible to add linuxmusl-armv6 and linuxmusl-armv7 prebuilds?

**Comment by lovell** [comment]
No, sorry, please see #19 and #59

**Comment by Rubber1Duck** [comment]
Thanks for your fast answer!

**Comment by lovell** [comment]
No problem, you're very welcome to try to roll your own using all the code and scripts in this repo, but I cannot provide any support.
