### ISSUE TITLE
Downloading sharp release fails with "zlib: unexpected end of file", continues to use node-gyp?

### ISSUE THREAD

**Issue by polarathene** [lovell/sharp-libvips#18]
I am aware of [prior issues with slow/failing installs](https://github.com/lovell/sharp-libvips/issues/5), I am also in China presently with a VPN. When the download fails, I get an error like below. My question is, afaik the error is because the download failed or (thinks it was successful?), continuing onto using node-gyp and looking for python? 

Is that the correct error/behaviour to expect? (Rather than avoid triggering node-gyp which I assume only should be done if the file was valid(eg passed checksum test)? I think the error is being raised [here](https://github.com/lovell/sharp/blob/master/install/libvips.js#L79) but it's not clear to me where it progresses towards node-gyp.

Additional question, what is node-gyp being used for here? I don't seem to need to have python installed if I provide my own local copy of the vendor content(extracted to packages /vendor directory), I guess because it passes the tests, is it requried for global libvips or remote pre-built binary sourcing only?

```
error /usr/local/share/.cache/yarn/v4/.tmp/5e088045120241bf9354ee531820b112.c7f5a07da6b02f6e23e872e8bb096a88c11ee395.prepare/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /usr/local/share/.cache/yarn/v4/.tmp/5e088045120241bf9354ee531820b112.c7f5a07da6b02f6e23e872e8bb096a88c11ee395.prepare/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
ERR! sharp zlib: unexpected end of file
ERR! sharp Please see http://sharp.pixelplumbing.com/page/install
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.19.12-2-MANJARO
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/share/.cache/yarn/v4/.tmp/5e088045120241bf9354ee531820b112.c7f5a07da6b02f6e23e872e8bb096a88c11ee395.prepare/node_modules/sharp
gyp ERR! node -v v10.15.0
success Saved lockfile.
```

**Comment by lovell** [comment]
The pre-built binaries of sharp are only guaranteed to work with the pre-built binaries of libvips.

If the download of a pre-built binary of libvips fails then sharp has to fall back to attempting to build itself from source.

http://sharp.pixelplumbing.com/en/stable/install/#pre-compiled-libvips-binaries provides information about serving the libvips binaries from a local URL.

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/cf62372cab3366ed5e1d42c1f13782825482de25 improves the install-time logging, thanks for the suggestion.

**Comment by nelson6e65** [comment]
I had to manually remove the `~/.npm/_libvips/libvips-8.7.0-linux-x64.tar.gz` and try again. Seems to be downloaded a corrupted file.

**Comment by zith5364** [comment]
$ npm install

> sharp@0.23.0 install /builds/stella/dummy/z_test_delete/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
/builds/stella/dummy/z_test_delete/node_modules/sharp/install/libvips.js:85
          throw new Error(`Status ${response.statusCode}`);
          ^

Error: Status 403
    at /builds/stella/dummy/z_test_delete/node_modules/sharp/install/libvips.js:85:17
    at f (/builds/stella/dummy/z_test_delete/node_modules/once/once.js:25:25)
    at f (/builds/stella/dummy/z_test_delete/node_modules/once/once.js:25:25)
    at ClientRequest.protocol.request.res (/builds/stella/dummy/z_test_delete/node_modules/simple-get/index.js:63:5)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
make: Entering directory '/builds/stella/dummy/z_test_delete/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:22: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
                      ^
compilation terminated.
sharp.target.mk:127: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/builds/stella/dummy/z_test_delete/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.14.123-111.109.amzn2.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /builds/stella/dummy/z_test_delete/node_modules/sharp
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-19T01_03_16_229Z-debug.log

**Comment by polarathene** [comment]
@zith5364  You should use markdown syntax for your log(which is the entire response, use 3 backticks on lines before and after the log you copy/pasted). Also your log does not have the error that this issue was about, why are you sharing it here? Create a new issue..

NPM tried to download the file, but got error 403 which is an HTTP error for "Forbidden", for some reason you did not have access/permission(firewall/proxy at company or something else like where you are in the world, China?). 

Because of that, the file could not be downloaded. The installation could not continue and fails(the remainder of the log).
