### ISSUE TITLE
Failing checksum

### ISSUE THREAD

**Issue by nicolai-markov** [lovell/sharp-libvips#184]
We're trying to install `libvips-8.14.2-linux-x64.tar.br` and am getting an integrity error:

```
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.2/libvips-8.14.2-linux-x64.tar.br
npm ERR! sharp: Integrity expected: sha512-wjCKmWfBb0uz1UB7rPDLvO0s+VWuoAY/Vv/YGCRFEQUkdSLQUgHExrOMMbOM3FleuYfQqznDYCXXphkl7X44+w==
npm ERR! sharp: Integrity received: sha512-Iyc3nXOhHTaxUTU2gbCDlcJslN9lVmTddR3eKb5oLMi7vEoN2dXdgcUGxihl+8ofNTTua1hHjI8ouZqr5CzrlA==
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: Integrity check failed for linux-x64
```

When looking in the integrity file (https://github.com/lovell/sharp-libvips/releases/download/v8.14.2/libvips-8.14.2-linux-x64.tar.br.integrity) this is the sha512 that it's expecting, but it doesn't match the actual checksum of the file.

**Comment by lovell** [comment]
Did you see https://github.com/lovell/sharp-libvips/issues/183 ? I ask as it looks like you might both work for the same company.

**Comment by nicolai-markov** [comment]
Thanks. Yes, we connected on that this morning after I had posted it. Appreciate the guidance. We still haven't been able to resolve it though. But I agree it is most likely on our connection and failing to get the file downloaded.
