### ISSUE TITLE
Can't install sharp

### ISSUE THREAD

**Issue by anutator** [lovell/sharp-libvips#185]
I install Directus extensions in docker container directus/directus:10.2.1 and sharp is a dependency

https://github.com/lovell/sharp-libvips/releases/download/v8.14.2/libvips-8.14.2-linuxmusl-x64.tar.br
```
#0 33.79 .../sharp@0.32.1/node_modules/sharp install: sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.2/libvips-8.14.2-linuxmusl-x64.tar.br
#0 33.79 .../sharp@0.32.1/node_modules/sharp install: sharp: Via proxy http://myproxy.com:13128 no credentials
#0 33.80 .../sharp@0.32.1/node_modules/sharp install: sharp: Installation error: tunneling socket could not be established, cause=read ECONNRESET
#0 33.80 .../sharp@0.32.1/node_modules/sharp install: sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
...
#0 33.88 .../sharp@0.32.1/node_modules/sharp install: Failed
#0 33.88  ELIFECYCLE  Command failed with exit code 1.

```
besides I'd like to download **tar.gz**, not **tar.br**. My command to install packages

```
pnpm install $EXTENSIONS --config.platform=linux --config.architecture=x64
```

**Comment by lovell** [comment]
> sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.2/libvips-8.14.2-linuxmusl-x64.tar.br
> sharp: Via proxy http://myproxy.com:13128 no credentials
> sharp: Installation error: tunneling socket could not be established, cause=read ECONNRESET

This looks like a networking problem between your web proxy and github.com. You'll need to ensure the proxy is capable of and/or permits TLS traffic to/from github.com.
