### ISSUE TITLE
Pdfium include in build script?

### ISSUE THREAD

**Issue by talberkoMelio** [lovell/sharp-libvips#188]
Hi,
Do you have an example of how to build it with pdfium? I didnt find it in the build script.

Thanks

**Comment by lovell** [comment]
Please see https://github.com/libvips/libvips#pdfium - sadly I cannot help you with pdfium so good luck.

**Comment by talberkoMelio** [comment]
@lovell it probably out of scope, but I am using Sharp with poppler for converting pdf to jpeg, the `toBuffer` command takes about ~25sec, so I thought maybe I should use pdfium instead of poppler. Do you know if compiling with pdfium may improve the performance over poppler?

The command I run for the PDF to jpeg:

`sharp(buffer, { page }).jpeg().toBuffer()`

**Comment by lovell** [comment]
I also cannot help with Poppler - good luck.

**Comment by bru02** [comment]
Here is how I managed to make it work: https://github.com/lovell/sharp-libvips/compare/main...bru02:sharp-libvips:main#diff-15fe4217ccf5f305b4bb5645dadf5970e32ed9d45d0366118a76376f8d0e1eae

**Comment by lovell** [comment]
Thank you for the update, great to hear you got it working.
