### ISSUE TITLE
npm install error --iOS  ( IONIC/ANGULAR Project )

### ISSUE THREAD

**Issue by pjdpaulsagnik** [lovell/sharp-libvips#189]
npm ERR! code 1
npm ERR! path /Users/user/Documents/APP_PUBLISH/BERGER-NEPAL-SAMBANDH-APP/Sambandh-Nepal/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c -- (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-darwin-arm64v8.tar.br
npm ERR! node:internal/fs/utils:347
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: EACCES: permission denied, copyfile '/tmp/15787-libvips-8.12.2-darwin-arm64v8.tar.br' -> '/Users/user/.npm/_libvips/libvips-8.12.2-darwin-arm64v8.tar.br'
npm ERR!     at Object.copyFileSync (node:fs:2847:3)
npm ERR!     at WriteStream.<anonymous> (/Users/user/Documents/APP_PUBLISH/BERGER-NEPAL-SAMBANDH-APP/Sambandh-Nepal/node_modules/sharp/install/libvips.js:204:20)
npm ERR!     at WriteStream.emit (node:events:513:28)
npm ERR!     at emitCloseNT (node:internal/streams/destroy:138:10)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   errno: -13,
npm ERR!   syscall: 'copyfile',
npm ERR!   code: 'EACCES',
npm ERR!   path: '/tmp/15787-libvips-8.12.2-darwin-arm64v8.tar.br',
npm ERR!   dest: '/Users/user/.npm/_libvips/libvips-8.12.2-darwin-arm64v8.tar.br'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2023-07-31T11_48_58_865Z-debug-0.log

npm dependency error for @capacitor/assets

"node_modules/@capacitor/assets": {
      "version": "2.0.4",
      "resolved": "https://registry.npmjs.org/@capacitor/assets/-/assets-2.0.4.tgz",
      "integrity": "sha512-1zYuwJujihsCLavojpZQQEjQjxG8BgD2/QWaX1Je2TQgN8UVbmnQG7gO+6gaHqP+hgZu7SOcJ+BlMG+tarBXLA==",
      "dev": true,
      "dependencies": {
        "@capacitor/cli": "^3.2.5",
        "@ionic/utils-array": "^2.1.5",
        "@ionic/utils-fs": "^3.1.5",
        "@trapezedev/project": "^5.0.5",
        "commander": "^8.3.0",
        "debug": "^4.2.0",
        "fs-extra": "^10.0.1",
        "node-fetch": "^2.6.7",
        "node-html-parser": "^5.3.3",
        "sharp": "^0.30.7",
        "tslib": "^2.0.3",
        "yargs": "^17.3.1"
      },
      "bin": {
        "capacitor-assets": "bin/capacitor-assets"
      },
      "engines": {
        "node": ">=10.3.0"
      }
    }

**Comment by lovell** [comment]
Cross-posted at https://github.com/ionic-team/capacitor-assets/issues/544 - please avoid cross-posting as it creates extra, unnecessary work for volunteer maintainers.

Please see https://sharp.pixelplumbing.com/install#common-problems especially the bits about npm and filesystem ownership.

It also looks like the `@capacitor/assets` dependency is not using the latest version of sharp, so https://github.com/ionic-team/capacitor-assets/pull/541 may be relevant.

If you're still having problems please open a new installation issue at https://github.com/lovell/sharp/issues/new?assignees=&labels=installation&projects=&template=installation.md ensuring you answer all of the questions.
