### ISSUE TITLE
libvips-8.7.0-linuxmusl-armv6

### ISSUE THREAD

**Issue by alrosot** [lovell/sharp-libvips#19]
Hello,
Would it be possible to add one more binary to release 8.7.0?
I'm building a docker image `FROM arm32v6/alpine` and I'm getting the following error as there is no 
libvips-8.7.0-linuxmusl-armv6.tar.gz available
```
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linuxmusl-armv6.tar.gz
/usr/src/app/node_modules/sharp/install/libvips.js:81
          throw new Error(`Status ${response.statusCode}`);
          ^

Error: Status 404
    at /usr/src/app/node_modules/sharp/install/libvips.js:81:17
```
Not sure what's the effort involved on that, but I'm happy to try to compile that version and send it back to be released.

Thank you!

**Comment by lovell** [comment]
Hello, these binaries are provided to help most of the people most of the time on the most common platform combinations. In this case you'll need to install [vips](https://pkgs.alpinelinux.org/package/edge/testing/armhf/vips) from apk or compile from source.

I'll improve the error handling for non-x64 musl-based Linux.

**Comment by alrosot** [comment]
I guess it makes sense to not cover all possible combinations. Thanks @lovell
