### ISSUE TITLE
Recommendations / improvements

### ISSUE THREAD

**Issue by kleisauke** [lovell/sharp-libvips#21]
Hi Lovell,

Thanks for these packaging scripts! I intend to use this in the next version of NetVips (https://github.com/kleisauke/net-vips/issues/21). 

I've made a number of improvements to [my fork](https://github.com/kleisauke/libvips-packaging) that you might be able to integrate as well.

Recommendations / improvements:
- There are a few unused shared libraries that could be removed (I didn't check the ARM* builds):
  <details>
  <summary>Unused shared libraries</summary>
  
  In `libvips-8.7.4-linux-x64.tar.gz`:
  ```
  libharfbuzz-subset.so.0
  libwebpdemux.so.2
  ```
  
  In `libvips-8.7.4-linuxmusl-x64.tar.gz`:
  ```
  libasprintf.so.0
  libharfbuzz-subset.so.0
  libwebpdemux.so.2
  ```
  
  In `libvips-8.7.4-darwin-x64.tar.gz`:
  ```
  libasprintf.0.dylib
  libcairo-gobject.2.dylib
  libcairo-script-interpreter.2.dylib
  libharfbuzz-gobject.0.dylib
  libharfbuzz-icu.0.dylib
  libharfbuzz-subset.0.dylib
  liborc-test-0.4.0.dylib
  libpcre16.0.dylib
  libpcre32.0.dylib
  libpcrecpp.0.dylib
  libpcreposix.0.dylib
  libtiffxx.5.dylib
  libwebpdecoder.3.dylib
  libwebpdemux.2.dylib
  ```
  </details>

  I fixed this by copying only the relevant shared libraries to the final `lib/` directory using the `ldd` and `otool` commands (see [here](https://github.com/kleisauke/libvips-packaging/blob/5c69bb985a566ff8f2d03a5f4bc6bf8e71599a64/build/lin.sh#L300-L307) and [here](https://github.com/kleisauke/libvips-packaging/blob/5c69bb985a566ff8f2d03a5f4bc6bf8e71599a64/build/osx.sh#L17-L45)). This also removes all the symlinks in the packaging.
- You might consider to use the [build-win64-mxe](https://github.com/libvips/build-win64-mxe) distribution for Windows (see https://github.com/libvips/build-win64/issues/22).
- Perhaps we should experiment with building a statically linked library on Linux and OS X (I did [the same](https://github.com/libvips/build-win64/issues/21#issuecomment-458112440) for the Windows build).  This may resolve conflicts with the system `zlib` in the future.

Some things I came across during the building process:
- The [OS X build](https://github.com/lovell/package-libvips-darwin) currently fails on Travis with:
  ```
  Error: Options --build-from-source and --build-bottle are mutually exclusive.
  ```
  I removed the `--build-bottle` flag, but I'm not sure if it will still be built with `-march=core2` (to ensure that it will work on non-AVX Intel CPUs).
- The x64 musl build currently generates a non-working `libuuid` library (https://bugs.alpinelinux.org/issues/9947):
  ```
  $ ldd libvips.so.42
  ...
  Error relocating ./libuuid.so.1: getrandom: symbol not found
  ```
  I "duct tape" fixed this by copying your `libuuid.so.1` to my final `lib/` directory. We should keep an eye on that issue.

**Comment by lovell** [comment]
Thanks Kleis, I definitely want to migrate to using https://github.com/libvips/build-win64-mxe for Windows as an increasing number of dependencies are moving away from autotools (and therefore are no longer jhbuild-able).

Are all those unused shared libraries really unused, e.g. I'd expect `libwebpdemux` to be required for reading WebP metadata?

I avoided static libs due to the licensing complexities but happy to revisit. My guiding principle is that these binaries are provided to help most people most of the time so they won't work for everyone all the time ;)

The OS X "build" is probably failing due to the recent homebrew changes to remove pretty much all options from packages so will need a bit of TLC.

The libuuid `getrandom` problem can be dealt with via the same approach taken for [expat](https://github.com/lovell/sharp-libvips/blob/master/build/lin.sh#L209) (coincidentally I know Peter who opened the musl issue you linked to.)

**Comment by kleisauke** [comment]
I have also noticed that a number of dependencies are moving away from autotools. JHBuild should work with Meson (many GNOME dependencies move to this build system), but I think it requires some adjustments if you want to build `librsvg` with it (which requires the Rust toolchain). `librsvg` is furthermore difficult to build into a cross compiler, see for e.g. this patch:
https://gitlab.gnome.org/GNOME/librsvg/issues/239#note_425622

vips 8.7.4 doesn't need `libwebpdemux`. It's only required while building vips 8.8:
https://github.com/libvips/libvips/commit/801a2a71443c33679ae9a18a1c9f8db8764152e4#diff-67e997bcfdac55191033d57a16d1408aR1039

Indeed, building a statically linked library requires some licensing research. Also, static libs has the disadvantage that you can't just swap a dependency for a newer component, it always requires you to rebuild everything.

Homebrew's recent policy of removing all options from the formulas has not been helpful for people who want to customize it. Perhaps creating a [third-party tap](https://docs.brew.sh/Taps) for libvips will be helpful.

Thanks for the hint to solve the libuuid `getrandom` problem. Configuring libuuid with `ac_cv_func_getrandom=no` seems to fix this, see: https://github.com/kleisauke/libvips-packaging/commit/4dfb8e9f50e0ae16d4c6349caff20406bddc920b.

**Comment by lovell** [comment]
Quick update: the https://github.com/lovell/package-libvips-darwin repo is now a "tap" to contain the customised formulae so the OS X build is working again.

**Comment by kleisauke** [comment]
I noticed that the `versions.json` in the `libvips-8.7.4-linuxmusl-x64.tar.gz` tarball prints literal `\n` instead of a new line:
```
{\n  "cairo": "1.16.0",\n  "croco": "0.6.12",\n  "exif": "0.6.21",\n  "expat": "2.2.6",\n  "ffi": "3.2.1",\n  "fontconfig": "2.13.1",\n  "freetype": "2.10.0",\n  "fribidi": "1.0.5",\n  "gdkpixbuf": "2.36.12",\n  "gettext": "0.19.8.1",\n  "gif": "5.1.4",\n  "glib": "2.56.4",\n  "gsf": "1.14.45",\n  "harfbuzz": "2.3.1",\n  "jpeg": "2.0.2",\n  "lcms": "2.9",\n  "orc": "0.4.28",\n  "pango": "1.42.4",\n  "pixman": "0.38.0",\n  "png": "1.6.34",\n  "svg": "2.45.5",\n  "tiff": "4.0.10",\n  "uuid": "2.33.1",\n  "vips": "8.7.4",\n  "webp": "1.0.2",\n  "xml": "2.9.9",\n  "zlib": "1.2.11"\n}
```

The other tarballs doesn't seem to be affected. Perhaps we should use `printf` [here](https://github.com/lovell/sharp-libvips/blob/master/build/lin.sh#L306) because it has a more consistent behavior than `echo`.

**Comment by kleisauke** [comment]
Also, the Linux x64 build is currently broken because Wheezy (Debian 7) has recently been removed from the mirror network (see [announcement](https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html)).

It can be fixed with this patch:
```diff
diff --git a/linux-x64/Dockerfile b/linux-x64/Dockerfile
index 1111111..2222222 100644
--- a/linux-x64/Dockerfile
+++ b/linux-x64/Dockerfile
@@ -5,7 +5,10 @@ MAINTAINER Lovell Fuller <npm@lovell.info>
 
 # Build dependencies
 RUN \
-  echo "deb http://ftp.debian.org/debian wheezy-backports main" | tee /etc/apt/sources.list.d/wheezy-backports.list && \
+  # https://unix.stackexchange.com/a/508728
+  echo "deb [check-valid-until=no] http://archive.debian.org/debian wheezy-backports main" | tee /etc/apt/sources.list.d/wheezy-backports.list && \
+  echo "deb http://archive.debian.org/debian wheezy main" > /etc/apt/sources.list && \
+  echo "deb http://archive.debian.org/debian-archive/debian-security/ wheezy/updates main" >> /etc/apt/sources.list && \
   apt-get update && \
   apt-get install -y build-essential gcc-4.9-backport prelink autoconf libtool nasm gtk-doc-tools texinfo gperf advancecomp libglib2.0-dev gobject-introspection && \
   apt-get -t wheezy-backports install -y jq cmake && \
```

However, I think a better solution is to switch the Docker image to Debian 9 (codenamed stretch).

**Comment by lovell** [comment]
We need to continue to support RHEL7, which provides glibc 2.17. The earliest Debian still supported is 8/Jessie (until June 30, 2020), which provides glibc 2.19.

The binary compatibility between glbc 2.17 and 2.19 is very close, with a couple of additional pthread-related symbols - see https://abi-laboratory.pro/index.php?view=compat_report&l=glibc&v1=2.17&v2=2.18&obj=4c492&kind=abi#Added - so we should be OK to upgrade Debian to 8, ensuring we test on RHEL7 (or CentOS7 or similar).

Your `echo` to `printf` switch sounds like a good idea - I should probably add a test for the problem you found - happy to accept a PR if you're able.

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp-libvips/commit/acd9d57952969001143fd84b329c122a93513ce9 upgrades the linux-x64 container to Debian 8.

**Comment by lovell** [comment]
@kleisauke Commit https://github.com/lovell/sharp-libvips/commit/af36b7469a05bdf84d9840c3219622d8d7409fe5 adds what I think is the remainder of your suggestions from this issue and comments on other commits. Thank you very much for providing all these ideas and feedback.

**Comment by kleisauke** [comment]
Looks good! 👍

I think we're done, I'll close this issue.

**Comment by kleisauke** [comment]
I recently noticed some Windows 32-bit related problems on the sharp issue tracker. I think you could point them to https://github.com/libvips/build-win64-mxe/releases.

These releases are tested on the libvips test suite on both 64-bit and 32-bit Windows.

**Comment by lovell** [comment]
Thanks, have created https://github.com/lovell/sharp-libvips/issues/24 to track this (but refrained from describing it as "experiment with mexxy").
