### ISSUE TITLE
License Discrepency

### ISSUE THREAD

**Issue by byronhulcher** [lovell/sharp-libvips#210]
Hello, thank you for your work on this project.  I have a question about the license this code is distributed under.  Here in the GitHub repo you currently offer the code under an Apache 2.0 license.  

![image](https://github.com/lovell/sharp-libvips/assets/2479295/01036c45-50a9-4528-afda-94bfbc24358c)

However your npm package is distributed under an LGPL license 

![image](https://github.com/lovell/sharp-libvips/assets/2479295/c72d0833-517d-4430-87a8-5654567a27f9)

Can you clarify which license or licenses apply to this code? Thank you!

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
