### ISSUE TITLE
SVG embedding local files

### ISSUE THREAD

**Issue by muyichuanqi** [lovell/sharp-libvips#216]
SVG embedding local files

<svg>
<image xlink:href="file://d:xxx/xxx,png"/>
</svg>

Can we do this? Base64 is too big

**Comment by muyichuanqi** [comment]
<image xlink:href="file://d:/xxx/xx.png"/>

**Comment by muyichuanqi** [comment]
`<image xlink:href="file://d:/xxx.png"/>`

**Comment by lovell** [comment]
Cross-posted at https://github.com/lovell/sharp/issues/3968, please don't do that.
