### ISSUE TITLE
Invalid engine requirement for yarn

### ISSUE THREAD

**Issue by cristian-ratoi** [lovell/sharp-libvips#222]
Having that yarn doesn't have a version 3.x.x, shouldn't the engine requirement be something like `>=1.2.0`?

Is there something that I am missing?

I saw that there are multiple projects affected in npm workspace.

**Comment by lovell** [comment]
The Yarn package manager is currently on version 4.1.0.

https://yarnpkg.com/getting-started/install

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
