### ISSUE TITLE
GLIBC and AWS Lambda

### ISSUE THREAD

**Issue by deftomat** [lovell/sharp-libvips#23]
We just tried to use libvips generated by `./build.sh 8.7.4 linux-x64` in AWS lambda and Sharp is failing with the following error:

```
Something went wrong installing the "sharp" module

/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /opt/sharp/build/Release/../../vendor/lib/librsvg-2.so.2)

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```

Looks like commit https://github.com/lovell/sharp-libvips/commit/acd9d57952969001143fd84b329c122a93513ce9 introduces a dependency on GLIBC 2.19. However, AWS Lambda environment has v2.17.

**Comment by lovell** [comment]
Hi, is this with Node 8 only or both Node 8 and 10 (Amazon Linux 2)?

https://aws.amazon.com/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/

**Comment by lovell** [comment]
> "Amazon Linux 2 comes with GCC 7.3, Glibc 2.26, and Binutils 2.29.1"
> https://aws.amazon.com/amazon-linux-2/release-notes/ 

It looks like this problem is only going to occur on the deprecated Lambda runtime environment that reaches end-of-life on the 29th July.

**Comment by deftomat** [comment]
We are using node 8 lambdas. Not sure about v10

**Comment by deftomat** [comment]
Anyway, I didn't know that AWS already supports v10. Thank you for letting me know. I'm going to try it with v10. 😉

**Comment by lovell** [comment]
This error can also be seen on RHEL 7 and its derivatives e.g. CentOS 7, which use glibc 2.17.

It looks like the rust toolchain used by librsvg takes advantage of features of glibc 2.18 - see https://github.com/rust-lang/rust/issues/36826

This means the prebuilt binaries will drop support for RHEL 7 from sharp v0.23.0+.

RHEL 8, upon which Amazon Linux 2 is based, works correctly.

**Comment by kleisauke** [comment]
Isn't Amazon Linux 2 based on RHEL 7? Also note that CentOS 8 has [not yet been released](https://wiki.centos.org/About/Building_8) (I noticed that it was mentioned in [this commit](https://github.com/lovell/sharp/commit/ac60197dacaa5a4033fa48ac4fc06cb579dc2a5d#diff-64407d3e6d5ef382426bdfbcae040c6aR46)).

Perhaps we could try to build the Linux binaries on CentOS 7 (glibc 2.17) to make sure they are compatible on RHEL 7, Amazon Linux 2 and possibly on Debian 7 as well.

**Comment by kleisauke** [comment]
Also, could the musl docker image be based on Alpine 3.10 (musl libc 1.1.22)? I guess musl libc 1.1.20 and 1.1.22 [are binary compatible](https://abi-laboratory.pro/?view=timeline&l=musl). 

The latest versions of musl libc have several threads and stack size improvements (for e.g. the default thread stack size has been increased from 80k to 128k, which may help https://github.com/libvips/libvips/issues/1287).

As a side note,
If you are going to update Fontconfig to 2.13.91, you can also remove the UUID dependency (which was added with commit https://github.com/lovell/sharp-libvips/commit/e67bfd601fb20afbcae301fc7942608cbb3caed9), see:
https://cgit.freedesktop.org/fontconfig/commit/?id=c4324f54ee16e648ba91f3e9c66af13ab3b1754c
Hopefully Fontconfig will soon be updated within Homebrew as well to fix https://github.com/lovell/package-libvips-darwin/pull/3#issuecomment-490858840.

**Comment by lovell** [comment]
Amazon Linux 2 provides glibc 2.26, which makes it more like Fedora 27 in that respect.

I didn't realise CentOS 8 was still being built. If we can create a CentOS 7 based container able to run the existing lin.sh script then that would provide support for glibc 2.17+.

Thanks for the tip about removing uuid - I've done this in ca94439

**Comment by kleisauke** [comment]
I tried a CentOS 7 based container and it seems to build (I still have to test the binaries). See commit https://github.com/kleisauke/libvips-packaging/commit/e2f98194fd57f15c766ca43bfe440aa0d9051cd6.

Also, it seems Fontconfig 2.13.91 is a preview release (Homebrew didn't want to update to this version), perhaps we need to pinpoint it to 2.13.1.

**Comment by lovell** [comment]
@kleisauke Thank you! I borrowed most of your CentOS 7 work in commit https://github.com/lovell/sharp-libvips/commit/40807628dcf379753585f202a895bbd33a6fbeb3 and used it to create the binaries for libvips v8.8.1 (as used by sharp v0.23.0).
