### ISSUE TITLE
HEIF/HEIC support in sharp-libvips not working despite being included in lin.sh

### ISSUE THREAD

**Issue by nestarz** [lovell/sharp-libvips#233]
Hello, I noticed that in the `lin.sh` file located at https://github.com/lovell/sharp-libvips/blob/main/build/lin.sh, there is a line that specifies the version of HEIF support:

```
VERSION_HEIF=1.17.6
```

This suggests that the prebuilt binaries of libvips used by the sharp library should include support for HEIC images. However, when I try to use sharp to process HEIC images, I get the following error:

```
heif: Unsupported feature: Unsupported codec (4.3000)
```

It seems that even though the `lin.sh` script includes dependencies for HEIF, the sharp library is unable to make use of them.

My question is: What is the purpose of adding HEIF dependencies in `lin.sh` if sharp doesn't utilize them? Is there a way to enable HEIC support in sharp using these prebuilt binaries, or is there something else that needs to be done to make it work?

I would appreciate any clarification or guidance on this matter. If there are any additional steps or configurations required to enable HEIC support in sharp, please let me know.

Thank you for your attention to this issue.

**Comment by lovell** [comment]
> What is the purpose of adding HEIF dependencies in lin.sh if sharp doesn't utilize them? 

HEIF is a container used for AVIF (AV1) images, which are supported. The same container can be used to store HEIC (HEVC) images, which are unsupported. Both codecs are patented, but AV1 is royalty-free.

**Comment by nestarz** [comment]
Thank you @lovell, and for your work !

If I want to add HEIC (HEVC) support with HEIC that's the only file to edit ?
