### ISSUE TITLE
LGPL-3.0 licensing and Snyk notice for client-side use

### ISSUE THREAD

**Issue by devevignesh** [lovell/sharp-libvips#246]
Hello, we have encountered a Snyk notice regarding the use of the sharp library, specifically due to the LGPLv3 license under which the prebuilt `libvips`. We are using `sharp` in a Next.js application. Below is the Snyk issue we received:

> We have detected the use of one of the following licenses: GPL, AGPL, LGPL, EPL, or MPL. If the code runs on the client side (e.g., in a browser) or is distributed: This dependency/library must be removed. If the code runs on the server side (e.g., in a microservice) under the AGPL license: This dependency/library must be removed. If the code runs on the server side (e.g., in a microservice) under GPL, LGPL, EPL, or MPL licenses and you have not modified the library (i.e., you are simply using it as a dependency): You can ignore this Snyk issue.

**Comment by lovell** [comment]
- sharp is made available under the terms of the Apache 2.0 licence.
- libvips is made available under the terms of the LGPLv2 or any later version.
- The prebuilt sharp uses prebuilt libvips as a shared library under the terms of the LGPLv3.
- The prebuilt libvips uses various other libraries as static dependencies under [various other terms](https://github.com/lovell/sharp-libvips/blob/main/THIRD-PARTY-NOTICES.md) all of which are compatible with LGPLv3.

If you are using sharp then you must comply with the terms of the Apache 2.0 licence.

It looks like Snyk's licensing checker might be making assumptions about the consumption model of LGPL code, e.g. how does it detect derivatives vs clear separation e.g. via a shared library? It's also possible that someone at your organisation has configured Snyk with a set of "rules" about permitted licences, in which case you should speak with that person.

See also https://github.com/lovell/sharp/issues/3565 and https://github.com/lovell/sharp/issues/4023
