### ISSUE TITLE
Enhancement: consider HEIC support via libde265 (LGPL)+Kvazaar (BSD)

### ISSUE THREAD

**Issue by DimitarNestorov** [lovell/sharp-libvips#248]
[libheif already supports them](https://github.com/strukturag/libheif?tab=readme-ov-file#supported-features) and they're not GPL licensed

**Comment by lovell** [comment]
For HEIC the limiting factor is HEVC patents rather than software licences. The prebuilt binaries will only support patent-encumbered codecs that are made available on a royalty-free basis. HEVC is not royalty-free.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
