### ISSUE TITLE
Investigate SIMD-accelerated zlib implementations

### ISSUE THREAD

**Issue by kleisauke** [lovell/sharp-libvips#25]
It might be worth switching to a performance-oriented fork of the popular zlib library within the prebuild libvips binaries. Several companies have made zlib significantly faster by using modern CPU instructions (SSE, ARM NEON).

The [zlib-ng project](https://github.com/zlib-ng/zlib-ng) seems the most promising, it has merged the changes of both [Cloudflare](https://github.com/cloudflare/zlib) and [Intel](https://github.com/jtkukunas/zlib ) forks and cleans up the code in general. It's API / ABI compatible with zlib (when configured with `--zlib-compat` or `-DZLIB_COMPAT=ON`), so it can be used as a drop-in replacement (just like libjpeg-turbo).

There is no "stable" release for zlib-ng yet, so it might be too risky to migrate now. However, it's already been continuously fuzzed by OSS-Fuzz<sup>[1]</sup> and the Chromium / AOSP developers are also interested in switching to this fork<sup>[2][3]</sup>.

I've already done some experiments with zlib-ng within the MXE-based Windows builds<sup>[4]</sup>, and see a nice performance improvement by converting a 4,000 x 5,000 JPEG image to PNG with different compression values<sup>[5]</sup>.

<sup>[1]</sup> https://github.com/google/oss-fuzz/tree/master/projects/zlib-ng
<sup>[2]</sup> https://crbug.com/687631
<sup>[3]</sup> https://groups.google.com/a/chromium.org/d/msg/blink-dev/T3rPfd6G6ps/l8pAk7gnBgAJ
<sup>[4]</sup> https://github.com/libvips/build-win64-mxe/tree/zlib-ng-experiment
<sup>[5]</sup> https://gist.github.com/kleisauke/879e3075a675c6f945dff3772d2ef0a3

**Comment by lovell** [comment]
Thanks, I think we'd want to wait for a stable/supported release before making the switch.

I recall some of the Cloudflare changes were GPL-licenced but it doesn't look like these made it across.

**Comment by lovell** [comment]
There's a release candidate of zlib-ng at https://github.com/zlib-ng/zlib-ng/releases/tag/v2.0.0-RC1

**Comment by lovell** [comment]
I've created a [WIP branch](https://github.com/lovell/sharp-libvips/compare/zlibng) that switches to the latest zlib-ng release candidate (RC2).

https://github.com/lovell/sharp-libvips/actions/runs/607358257

The sharp tests pass locally on Linux x64 using the resultant binary too.

**Comment by klouvas** [comment]
i will create a WIP branch in our project and provide feedback. Thank you :)
