### ISSUE TITLE
Linux: patch libcairo if v1.17.2 is still latest release

### ISSUE THREAD

**Issue by lovell** [lovell/sharp-libvips#28]
See https://github.com/lovell/sharp/issues/1895 for context and https://gitlab.freedesktop.org/cairo/cairo/commit/2d1a137f3d27b60538c58b25e867288c7b0b61bc.diff for the necessary patch.

**Comment by marek-obuchowicz** [comment]
May I help you anyhow with this issue?

**Comment by kleisauke** [comment]
fwiw, https://gitlab.freedesktop.org/cairo/cairo/merge_requests/12 should also fix this. 

It's a little unfortunate that Cairo has not yet released a new version that solves this.

**Comment by marek-obuchowicz** [comment]
Are you aware of any workaround? Is there a way to make `sharp` use older pre-built libraries?
Seems that Cairo team does not have huge motivation to release this fix soon...

**Comment by lovell** [comment]
It might be better to roll back to the proven-more-stable cairo v1.16.0 with the next release of the prebuilt binaries

(I intend the next release of these binaries to include the as-yet-unreleased libvips v8.9.0 and will require the as-yet-unreleased sharp v0.24.0.)

**Comment by lovell** [comment]
I've rolled back to v1.16.0. Please subscribe to https://github.com/lovell/sharp/issues/1895 for notification of the next release with this change.

**Comment by lovell** [comment]
cairo v1.17.4 was released a couple of weeks ago and contains the fix for the original problem so commit 7d00bbc unpins to the latest version again.
