### ISSUE TITLE
Problem to use sharp / libvips on Docker / Dokku

### ISSUE THREAD

**Issue by templth** [lovell/sharp-libvips#29]
Hello,

I'm trying to use the sharp module within a nodejs application and it works fine locally on Ubuntu. Now I want to deploy this application on our server as a dokku application. This application relies on a Dockerfile that initializes elements:

```
FROM node:8.9.0

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app

EXPOSE 5000

CMD [ "npm", "start" ]
```

During the execution of the `npm install` task, I can see traces regarding `sharp` and things seem successful:

```
> sharp@0.23.3 install /usr/src/app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
```

However, when I'm trying to use the endpoint relying on `sharp`, the application crashes.

I guess that some required libraries are missing because it's a minimal distribution within the docker image but can't find what to add.

Thanks for your help!
Thierry

**Comment by lovell** [comment]
Is `/usr/src/app/node_modules` being overwritten by the `COPY . /usr/src/app` command?

**Comment by templth** [comment]
Thanks very much for your answer!

For testing, I changed the `Dockerfil` with this:

```
FROM node:8.9.0

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY . /usr/src/app/
RUN npm install

EXPOSE 5000

CMD [ "npm", "start" ]
```

and I have the same problem!

I can see that the file `libvips-8.8.1-linux-x64.tar.gz` is still downloaded...

**Comment by lovell** [comment]
Does upgrading the version of Node.js help (v8.9.0 is over 2 years old)? What is the output of `RUN npm install --verbose` within the container?

**Comment by templth** [comment]
This works with Node 10!

Thanks very much for your help!
