### ISSUE TITLE
Build error on RHEL8 ppc64le … fatal error: vips/vips8: No such file or directory

### ISSUE THREAD

**Issue by trekker** [lovell/sharp-libvips#34]
Everything works on my MAC, but now I need to install on ppc64le running RHEL8.  Looks like something is missing for building/compiling sharp-libvips on ppc64le architecture.  Would you please help me resolve this issue?

[flame@flame02 auth-server]$ yarn install
yarn install v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⢀ ibm_db: 0.33% | 73728 bytes downloaded out of 22151131 bytes.
[2/4] ⢀ dtrace-provider: ok
[3/4] ⢀ sharp: CXX(target) Release/obj.target/sharp/src/common.o
[-/4] ⢀ waiting...
error /home/flame/auth-server/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /home/flame/auth-server/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-ppc64.tar.gz
/home/flame/auth-server/node_modules/sharp/install/libvips.js:85
          throw new Error(`Status ${response.statusCode}`);
          ^

Error: Status 404
    at /home/flame/auth-server/node_modules/sharp/install/libvips.js:85:17
    at f (/home/flame/auth-server/node_modules/once/once.js:25:25)
    at ClientRequest.<anonymous> (/home/flame/auth-server/node_modules/simple-get/index.js:63:5)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:210:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.13.1 | linux | ppc64
gyp info find Python using Python version 2.7.5 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/home/flame/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/flame/auth-server/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/flame/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/flame/.cache/node-gyp/12.13.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/flame/.cache/node-gyp/12.13.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/flame/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/flame/.cache/node-gyp/12.13.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/flame/auth-server/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/flame/auth-server/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory `/home/flame/auth-server/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/flame/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 3.10.0-862.el7.ppc64le
gyp ERR! command "/home/flame/.nvm/versions/node/v12.13.1/bin/node" "/home/flame/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/flame/auth-server/node_modules/sharp

**Comment by lovell** [comment]
Prebuilt binaries for PowerPC are not provided so you'll need to install libvips yourself.

https://sharp.pixelplumbing.com/en/stable/install/#linux

**Comment by trekker** [comment]
I made some progress with building binaries for PowerPC, but it is still not working and I don't see enough detail to know what to do next.  Can you provide any help?  Here's what I can see....

```
ls -al /usr/local/lib
-rw-r--r--.  1 root root    59314 Jan  2 13:13 libgif.a
lrwxrwxrwx.  1 root root       11 Jan  2 13:13 libgif.so -> libgif.so.7
lrwxrwxrwx.  1 root root       15 Jan  2 13:13 libgif.so.7 -> libgif.so.7.2.0
-rwxr-xr-x.  1 root root    75432 Jan  2 13:13 libgif.so.7.2.0
-rw-r--r--.  1 root root  2070036 Jan  2 13:10 libpng16.a
-rwxr-xr-x.  1 root root      937 Jan  2 13:10 libpng16.la
lrwxrwxrwx.  1 root root       19 Jan  2 13:10 libpng16.so -> libpng16.so.16.37.0
lrwxrwxrwx.  1 root root       19 Jan  2 13:10 libpng16.so.16 -> libpng16.so.16.37.0
-rwxr-xr-x.  1 root root  1219328 Jan  2 13:10 libpng16.so.16.37.0
lrwxrwxrwx.  1 root root       10 Jan  2 13:10 libpng.a -> libpng16.a
lrwxrwxrwx.  1 root root       11 Jan  2 13:10 libpng.la -> libpng16.la
lrwxrwxrwx.  1 root root       11 Jan  2 13:10 libpng.so -> libpng16.so
-rw-r--r--.  1 root root 27087730 Jan  2 14:32 libvips.a
-rw-r--r--.  1 root root  6693306 Jan  2 14:32 libvips-cpp.a
-rwxr-xr-x.  1 root root     1081 Jan  2 14:32 libvips-cpp.la
lrwxrwxrwx.  1 root root       22 Jan  2 14:32 libvips-cpp.so -> libvips-cpp.so.42.11.3
lrwxrwxrwx.  1 root root       22 Jan  2 14:32 libvips-cpp.so.42 -> libvips-cpp.so.42.11.3
-rwxr-xr-x.  1 root root  2640792 Jan  2 14:32 libvips-cpp.so.42.11.3
-rwxr-xr-x.  1 root root     1027 Jan  2 14:32 libvips.la
lrwxrwxrwx.  1 root root       18 Jan  2 14:32 libvips.so -> libvips.so.42.11.3
lrwxrwxrwx.  1 root root       18 Jan  2 14:32 libvips.so.42 -> libvips.so.42.11.3
-rwxr-xr-x.  1 root root 13362968 Jan  2 14:32 libvips.so.42.11.3
drwxr-xr-x.  2 root root       76 Jan  2 14:33 pkgconfig
```


```
[flame@flame03 auth-server]$ npm install

> sharp@0.23.4 install /home/flame/auth-server/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.8.4
info sharp Building from source via node-gyp
make: Entering directory '/home/flame/auth-server/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
make: Leaving directory '/home/flame/auth-server/node_modules/sharp/build'
npm WARN flame2@0.0.4 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ppc64"})

added 2 packages from 60 contributors, removed 1 package and audited 5008 packages in 16.248s
found 0 vulnerabilities
```

```
[flame@flame03 auth-server]$ npm run server

> flame2@0.0.4 server /home/flame/auth-server
> nodemon server

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
Load client/src/test_options.json
isDebug() enabled
14:43:20.018 <dbjs> start

Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by lovell** [comment]
RHEL annoyingly doesn't search `/usr/local/lib` for shared libraries by default - see https://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries/17653893#17653893

**Comment by trekker** [comment]
Thank you.  That solved it!
