### ISSUE TITLE
docker ubuntu:latest error

### ISSUE THREAD

**Issue by djkloop** [lovell/sharp-libvips#35]
## Description

```sh
// The problem I encountered when using the gatsby library, 
// their libraries seem to depend on this library,
// It feels like a sharp problem.
```
[gatsby-issues(#20393)](https://github.com/gatsbyjs/gatsby/issues/20393)

### Steps to reproduce
```sh
# docker file 
FROM ubuntu:latest as builder

RUN apt-get update \
    && apt-get install -y python2.7 \
    && apt-get install -y python3.7 \
    && apt-get install -y python3-pip \
    && apt-get install -y libvips libvips-dev libvips-tools \
    && apt-get install -y glib2.0-dev \
    && apt-get install -y python-pip python-dev \
    && apt-get install -y curl

RUN rm /bin/sh && \
	ln -s /bin/bash /bin/sh

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN npm --version
RUN node -v

RUN npm i -g yarn

RUN npm i -g gatsby-cli
# Pull git project operation
...

RUN cd /tmp && yarn

// error

```

### Expected result
```sh
  Be able to install successfully
```
### Actual result

![image](https://user-images.githubusercontent.com/21050914/71720097-6505c500-2e5b-11ea-81eb-56498e33662f.png)

```sh
// Why did I install libvips and download it again?

// This package cannot be installed due to some network reasons in China, 
// so I chose to install libsvip with apt-get, but it seems to download the package again
```
![image](https://user-images.githubusercontent.com/21050914/71760103-34716a00-2ef3-11ea-8514-ad54f5ffa200.png)

### Environment

```sh
gatsby-cli@latest
```

**Comment by lovell** [comment]
Hi, you'll need to ensure the globally-installed libvips meets the minimum required version, e.g. for sharp v0.23.4 this is libvips v8.8.1.

https://sharp.pixelplumbing.com/en/stable/changelog/

There's a useful line in the error log you've provided that says "ERR! Please delete /root/.npm/_libvips/..." that should also help you.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
