### ISSUE TITLE
Is linux-x64 version compatible with Amazon Linux 1? 

### ISSUE THREAD

**Issue by asterikx** [lovell/sharp-libvips#49]
Is the `linux-x64` build compatible with Amazon Linux 1? I need to add vips to the Lambda Go runtime which is still at Amazon Linux 1 unfortunately

**Comment by lovell** [comment]
The linux-x64 build container currently uses CentOS 7 and therefore the binaries it creates require a minimum of glibc 2.17.

https://github.com/lovell/sharp-libvips/blob/master/linux-x64/Dockerfile#L4

Run `getconf GNU_LIBC_VERSION` to discover which glibc version you're running.

**Comment by asterikx** [comment]
It's actually at `glibc 2.17`. Thanks for your help @lovell 👍
