### ISSUE TITLE
Custom-built vendored libvips complains about missing dependencies

### ISSUE THREAD

**Issue by thatjuan** [lovell/sharp-libvips#56]
I'm trying to compile my own libvips so that I can add support for other image formats.

This topic has been discussed in a few /lovell/sharp issues, which I've read, but I haven't been able to get things working.

What I've tried so far is cloning this repo, then adding (to `lin.sh`):

```
mkdir ${DEPS}/heif
curl -Ls https://github.com/strukturag/libheif/releases/download/v${VERSION_HEIF}/libheif-${VERSION_HEIF}.tar.gz | tar xzC ${DEPS}/heif --strip-components=1
cd ${DEPS}/heif
./autogen.sh
./configure --host=${CHOST} --prefix=${TARGET} --enable-static --disable-shared --disable-dependency-tracking
make install-strip
```

And then removing the `--without-heif` build flag from vips. 

I then run `./build.sh 8.10.0 linux-x64`

The build works (using Docker on a mac host), and it produces a tarball.. In a separate ubuntu docker image, I install `sharp` and then manually replace the contents of `node_modules/sharp/vendor` with what's in the tarball above. 

I also had to change the libvips version in `package.json`

```
  "config": {
    "libvips": "8.10.0",
    "runtime": "napi",
    "target": 3
  }
```

I wrote a simple test script:

```
import * as sharp from 'sharp'

(async () => {

  await sharp(`./sample.heic`).toFormat('jpg').toFile('./sample.jpg')

})()
```

And when I run it, it complains that it can't find `libffi`. I then manually compiled and installed `libffi`, and then it complains that it can't find `libjpeg`:

```
/workspace/node_modules/sharp/lib/constructor.js:34
  throw new Error(error);
        ^
Error: 
Something went wrong installing the "sharp" module

libjpeg.so.8: cannot open shared object file: No such file or directory

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues
```

I could probably go on and install all libs manually, but this is probably a red flag. Isn't the custom `vendor` build I'm adding supposed to provide all of these? 

The end goal is to be able to run this inside of google cloud functions,  which will require some more work, but with this basic test failing I wanted to reach out for some feedback.

Thanks for putting this lib together 👍

**Comment by lovell** [comment]
>  I install sharp and then manually replace the contents of node_modules/sharp/vendor with what's in the tarball above.

sharp must be recompiled after updating any shared libraries upon which it depends. Run the `ldd node_modules/sharp/build/Release/sharp.node` command to see which shared libraries it expects vs which shared libraries it can find.

If you need to support HEIC input, you'll also need to add dependencies of libheif that allow you to do that e.g. libde265. Also note that libheif might depend on libjpeg, so the order in which these libraries are built and linked is important.

**Comment by thatjuan** [comment]
Thank you! That helps a lot. 

So if I provide `sharp_libvips_binary_host` pointing to my custom `sharp-libvips` build, and then install with `npm install --build-from-source`, it should work?

In a cloud function, having to compile at `install` time might slow down cold boots a lot. I should be able to solve that by also setting a custom `sharp_binary_host`, right?

I've added the dependencies of libheif to `lin.sh` as well.

I'll test this and report back. 👍

**Comment by thatjuan** [comment]
I tried the above, and I got `sharp-libvips` to build, then I put it in the `vendor/8.10.0` of a `sharp` checkout. I ran `npm install --build-from-source` there and it worked.

I then ran `npm pack`, and dropped the contents of the tarball it produced into `node_modules/sharp/` within my test project.

When I try to run it, though, I get:

```
$ /workspace/node_modules/.bin/ts-node index.ts
(node:39173) UnhandledPromiseRejectionWarning: Error: A boolean was expected
    at Promise (/workspace/node_modules/sharp/lib/output.js:856:15)
    at new Promise (<anonymous>)
    at Sharp._pipeline (/workspace/node_modules/sharp/lib/output.js:855:14)
    at Sharp.toFile (/workspace/node_modules/sharp/lib/output.js:66:19)
    at /workspace/index.ts:16:6
    at step (/workspace/index.ts:33:23)
    at Object.next (/workspace/index.ts:14:53)
    at /workspace/index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/index.ts:4:12)
(node:39173) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:39173) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

Any idea where I may be going wrong here?

**Comment by thatjuan** [comment]
I've switched to using vips from the master branch to test.

First, the artifacts of my build look like this: https://gist.github.com/thatjuan/8a55a09f7399a8cef0d01df5c9c345e2

I'm then running this, expecting the build to detect a system provided `libvips`, but I don't think it is

```LD_LIBRARY_PATH=/var/task/vendor/include:/var/task/vendor/lib:/var/task/vendor/share PKG_CONFIG_PATH=/var/task/vendor/lib/pkgconfig npm install --build-from-source https://github.com/lovell/sharp.git```

The output matches what I was seeing before:

```> sharp@0.26.0-beta1 install /var/task/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /root/.npm/_libvips/libvips-8.10.0-linux-x64.tar.br
make: Entering directory '/var/task/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
make: Leaving directory '/var/task/node_modules/sharp/build'
npm WARN saveError ENOENT: no such file or directory, open '/var/task/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/var/task/package.json'
npm WARN task No description
npm WARN task No repository field.
npm WARN task No README data
npm WARN task No license field.

+ sharp@0.26.0-beta1
added 72 packages from 164 contributors and audited 72 packages in 25.321s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities```

Shouldn't overriding `LD_LIBRARY_PATH` and `PKG_CONFIG_PATH` cause the build process to use a system provided lib?

Thanks again for your help so far. I hope I can contribute back to the project(s) soon 👍

**Comment by lovell** [comment]
If you're replacing the vendored binaries then `LD_LIBRARY_PATH` is not required. Are you setting `sharp_libvips_binary_host` as documented at https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries ?

**Comment by lovell** [comment]
@thatjuan Were you able to make progress with this?
