### ISSUE TITLE
No binary for linuxmusl-armv7

### ISSUE THREAD

**Issue by fastlorenzo** [lovell/sharp-libvips#59]
It would be great to have binaries for linuxmusl-armv7 as well.

I'm using RPi 4 with kubernetes and it some applications don't install because of Alpine containers using musl

**Comment by lovell** [comment]
No, sorry, see also #19 for a similar request. These scripts are all open source so please feel free to use what's in this repo to roll your own.

I might consider providing musl-based binaries for 64-bit ARM at some point in the future as I suspect this combo will become significantly more popular in the next few years.

**Comment by fastlorenzo** [comment]
I might have missed that one, thanks. I tried compiling it but it's not the easiest in term of cross-compilation ;)

I guess I'll have to try harder then! PS: I'll make a PR in case I manage to make it work, if it can help someone else ;)
