### ISSUE TITLE
Linux: link libvips with -Bsymbolic-functions

### ISSUE THREAD

**Issue by kleisauke** [lovell/sharp-libvips#60]
See https://github.com/kleisauke/libvips-packaging/commit/41fb70c9ae3dd237fb7f3e9924f7121505ca1b28 and https://github.com/kleisauke/net-vips/issues/90 for context. Could possibly resolve https://github.com/lovell/sharp/issues/575 (and other `node-canvas` related issues).

[GLib uses this linker flag by default](https://developer.gnome.org/glib/2.64/glib-building.html#extra-configuration-options), so it might make sense to also link libvips with this flag. The above NetVips issue had no issues running this on macOS, so I'm not sure if this flag is needed there as well (Homebrew also seems to avoid any `-Bsymbolic*` linker flags, probably due to missing support for this in Xcode(?)).

**Comment by lovell** [comment]
Nice idea, happy for a PR if you're able. This is an ELF-only feature so should be ignored by linkers for e.g. macOS targets.

**Comment by kleisauke** [comment]
Great, I'll prepare a PR. 

Ah, you're right, this linker flag only applies to ELF binaries and not to Mach-O, for example. I got confused since HarfBuzz seems to configure successfully with `-Bsymbolic-functions` on macOS, see:
```
C++ compiler for the host machine: clang++ (clang 11.0.3 "Apple clang version 11.0.3 (clang-1103.0.32.62)")
C++ linker for the host machine: clang++ ld64 556.6
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports link arguments -Bsymbolic-functions: YES 
```

**Comment by lovell** [comment]
(Re-opening auto-closed issue until we publish a new release.)

**Comment by mceachen** [comment]
At @lovell's suggestion, I've just opened https://github.com/electron/electron/issues/25495 (which may help other native modules).
