### ISSUE TITLE
Can you help compile a version with magic

### ISSUE THREAD

**Issue by banli17** [lovell/sharp-libvips#63]
I want to use the gif function, but it always fails during compilation

![image](https://user-images.githubusercontent.com/12556069/92700973-085f9000-f382-11ea-8a23-82417fa32fd2.png)

**Comment by lovell** [comment]
If this is for Windows, you'll need to base it on the "all" formats upstream release rather than only "web" formats.

https://github.com/libvips/build-win64-mxe

**Comment by banli17** [comment]
I don’t understand here, how to increase the dependency
![image](https://user-images.githubusercontent.com/12556069/92718621-9f354800-f394-11ea-9c27-ae908236be94.png)


In addition, it is not windows, but linux 64 。 Is this the command.

```
~] bash build.sh --PLATFORM="linux-x64"
```

![image](https://user-images.githubusercontent.com/12556069/92718859-f63b1d00-f394-11ea-95cf-80ca2ba13f3d.png)


Don't know why it became win

**Comment by lovell** [comment]
The docs at https://github.com/lovell/sharp-libvips#creating-a-tarball say:

> Run the top-level build script without parameters for help.

Doing so reveals:

```
$ ./build.sh 

Usage: ./build.sh VERSION [PLATFORM]
Build shared libraries for libvips and its dependencies via containers

Please specify the libvips VERSION, e.g. 8.9.2

Optionally build for only one PLATFORM, defaults to building for all

Possible values for PLATFORM are:
- win32-ia32
- win32-x64
- linux-x64
- linuxmusl-x64
- linux-armv6
- linux-armv7
- linux-arm64v8
- darwin-x64
```
So for example you might try the following:
```
$ ./build.sh 8.10.0 linux-64
```

A word of warning: modifying the scripts in this repo is not straightforward and will require experience with shell scripting and compiling Linux software from source.

**Comment by banli17** [comment]
Yes, it is more difficult for me. Do I have other ways to compile? I tried to compile directly with libvips, but it doesn’t have some dependencies by default, such as svg, I don’t know how to add

**Comment by banli17** [comment]
@lovell    
 I echoed a lot of breakpoints and found that it was a problem during version checking, possibly caused by my network. The compilation is successful, but I may need to clone a sharp to install my own sharp.

Do you think it is necessary for sharp to directly compile a version with magic, and then install this version by reading the configuration of package.json or other files when npm i sharp. There may be other users who need it, but it is too troublesome to compile by yourself

**Comment by banli17** [comment]
It has been successful. Install vips globally. Record it

1. First need to install some dependencies

```
yum install -y libjpeg* libpng* libtiff* libungif* freetype zlib
yum install ImageMagick
yum install ImageMagick-devel
yum install librsvg2-devel
```

If there is a loader library for some pictures (such as yum install librsvg2-devel), vips will be called, otherwise it will be processed by ImageMagick.

2. Follow the [libvips document](https://libvips.github.io/libvips/install.html) to install, the configuration should be noted:

```
./configure --with-magickpackage=ImageMagick --with-modules
```

![image](https://user-images.githubusercontent.com/12556069/93023741-82fb0a80-f623-11ea-83fc-95cb9b6ba08f.png)

**Comment by lovell** [comment]
Thanks for the update, glad to hear you got it working.

**Comment by danieljee** [comment]
Could you please post changes you've made on the bash script to enable imagemagick to be used by vips?
I tried installing imagemagick and set --with-magick flag but the output library wasn't using imagemagick
