### ISSUE TITLE
can't create avif using sharp-libvips 8.10.1-alpha2

### ISSUE THREAD

**Issue by grantbeattie** [lovell/sharp-libvips#65]
I'm attempting to convert a jpeg to avif using sharp 0.26.1 and prebuilt libvips 8.10.1-alpha2, however it looks like the required symbols from libaom aren't being pulled into the shared libvips:

```
$ node
Welcome to Node.js v12.18.4.
Type ".help" for more information.
> const sharp = require('sharp')
undefined
> sharp('test.jpg').toFormat('heif').toFile('test.heif')
Promise { <pending> }
> node: symbol lookup error: /app/sharp-0.26.1/build/Release/../../vendor/8.10.1/lib/libvips.so.42: undefined symbol: aom_codec_av1_cx
```

am I jumping the gun and trying to do this before it's ready? =)

**Comment by lovell** [comment]
Thank you for alpha testing this but yes, too early - please subscribe to https://github.com/lovell/sharp/issues/2289 for updates.

**Comment by grantbeattie** [comment]
ah, it does indeed work with this commit now 🎉 

https://github.com/lovell/sharp-libvips/commit/30a48e1857efb4c62ff06dd49704a94fb2e5ce9c
