### ISSUE TITLE
gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by Dramex** [lovell/sharp-libvips#68]
what i did was just :

`./build.sh 8.9.2 linux-x64`

**Comment by lovell** [comment]
This happens when there's a problem downloading the source code for one of the dependencies, perhaps due to a temporary networking problem.

**Comment by Dramex** [comment]
@lovell can you confirm if you get same issue because I'm trying for 2 days. i used different machines and network

**Comment by lovell** [comment]
> I'm trying for 2 days. i used different machines and network.

You'll need to work out where the [lin.sh](https://github.com/lovell/sharp-libvips/blob/master/build/lin.sh) script is failing. The log output just before the failure should indicate how far it had got.

> provide a ready-to-use lambda layer 

Please see https://github.com/lovell/sharp/issues/1772
