### ISSUE TITLE
Unpin meson from v0.55.3

### ISSUE THREAD

**Issue by lovell** [lovell/sharp-libvips#70]
See commit https://github.com/lovell/sharp-libvips/commit/3b0744318b078ce61c7fbe0ccbdf874bc04d92c4

```
Temporarily pin meson to 0.55.3 as latest 0.56.0 is failing

The problem appears to be that libraries listed in
Requires.private field of dependencies' pkg-config .pc files
are ignored when building meson subproject executables.

(We don't really care about these executables, but most
dependencies don't offer the option to skip building them.)

There are quite a few dependency-related changes in meson 0.56.0
so it's not obvious where this has broken.
```

**Comment by kleisauke** [comment]
I think the upcoming Meson v0.56.1 resolves this. This release should include commit https://github.com/mesonbuild/meson/commit/6d816c1800dd7e81238a0b4615b42a2802296f93.

The macOS build probably also needs to be temporarily pinned, see:
https://github.com/lovell/sharp-libvips/blob/b3d7b227936276f337e2c11c92dfaadc5de37c0c/.github/workflows/build-release.yml#L49
