### ISSUE TITLE
Prebuilts for Apple Silicons (darwin-arm64v8)

### ISSUE THREAD

**Issue by chengluyu** [lovell/sharp-libvips#71]
Hi, is there any plan to add prebuilts for darwin-arm64v8?

**Comment by lovell** [comment]
Yes, it is dependent on a CI provider making Apple Silicon M1 hardware available for free to open source projects. If anyone knows of one please add a comment (or better yet a PR to integrate with it).

Please see https://github.com/lovell/sharp/issues/2460 for some discussion about how to compile libvips from source on this new platform.

**Comment by chengluyu** [comment]
Thanks a lot! I should search in [lovell/sharp](https://github.com/lovell/sharp) first. I'm leaving this issue open. Feel free to close it.

**Comment by kleisauke** [comment]
I think you could also cross-compile for `aarch64-apple-darwin` on a `x86_64-apple-darwin` environment (or even on `x86_64-unknown-linux-gnu`). Note that dependencies built upon Rust (i.e. librsvg) require Rust to be installed via the beta channel, as Apple Silicon support only recently landed in Rust/Rustup. Perhaps we should wait for Rust 1.49 before considering this approach.

**Comment by abarisain** [comment]
> I think you could also cross-compile for `aarch64-apple-darwin` on a `x86_64-apple-darwin` machine 

In an happy coincidence, I actually worked on this today: https://github.com/lovell/sharp-libvips/pull/74 (very wip, probably unmergable in its current state due to the maintenance cost)

Ran into some libffi trouble (which was quite expected) as the python build script is bugged

librsvg can be worked around by using an older version. As detailed in the PR, macports did exactly that.

**Comment by lovell** [comment]
For anyone that has subscribed to this issue for updates, please see also https://github.com/lovell/sharp/issues/2604

**Comment by lovell** [comment]
sharp v0.28.0 is now available and provides prebuilt libvips binaries for darwin-arm64v8. Merci beaucoup for your help @abarisain!

**Comment by chengluyu** [comment]
Great! Thanks everyone!
