### ISSUE TITLE
Add linuxmusl-arm64 binaries

### ISSUE THREAD

**Issue by gpetrov** [lovell/sharp-libvips#72]
Could you please add linuxmusl-arm64 binary generation?

Currently only linuxmusl-x64 binaries are being generated and we need musl arm64 binaries for node-alpine.

Seems to me the current build script and docker images can handle it already, just need an extra build target.

It will be a great Christmas present - now that the pubs are closed :)

**Comment by lovell** [comment]
PR welcome if you're able.

**Comment by Casuallynoted** [comment]
+1 to this, currently trying to build a docker image that depends on libvips but it won't compile due to the binaries not being available. Won't compile either.

**Comment by gpetrov** [comment]
almost succeeded with the build for muse @lovell ! Fixed a very nasty issue with harfbuzz https://github.com/harfbuzz/harfbuzz/issues/2771

Just one final road block of some dependency mixture:
```
   Compiling glib v0.9.3
   Compiling librsvg_c_api v0.0.1 (/deps/svg/librsvg)
    Finished release [optimized] target(s) in 1m 10s
ar: `u' modifier ignored since `D' is the default (see `U')
  CCLD     librsvg-2.la
libtool:   error: object name conflicts in archive: .libs/librsvg-2.lax/librsvg_c_api.a//deps/svg/./.libs/librsvg_c_api.a
make[3]: *** [Makefile:998: librsvg-2.la] Error 1
make[3]: Leaving directory '/deps/svg'
make[2]: *** [Makefile:1277: install-recursive] Error 1
make[2]: Leaving directory '/deps/svg'
make[1]: *** [Makefile:1584: install] Error 2
make[1]: Leaving directory '/deps/svg'
```

any idea what that might be?

**Comment by gpetrov** [comment]
all solved - made it optional as it seems it was included by the dependencies.

here is the PR https://github.com/lovell/sharp-libvips/pull/73

**Comment by lovell** [comment]
PR #90 added this - I'm going to re-open this issue until we ship a release that uses it.

**Comment by lovell** [comment]
The new linuxmusl-arm64v8 libvips binaries are now tested as part of sharp's CI process, which means prebuilt linuxmusl-arm64 sharp binaries will also be provided from the next release - see https://travis-ci.org/github/lovell/sharp/builds/761832277

Thanks all for your help with this.
