### ISSUE TITLE
Undefined symbol when building with poppler

### ISSUE THREAD

**Issue by olivier-lacroix** [lovell/sharp-libvips#75]
Hi there,

I am trying to build libvips with PDF support. main additions to build/lin.sh are as follow:

```sh
mkdir ${DEPS}/openjpeg
$CURL https://github.com/uclouvain/openjpeg/archive/v${VERSION_OPENJPEG}.tar.gz | tar xzC ${DEPS}/openjpeg --strip-components=1
cd ${DEPS}/openjpeg
mkdir build
cd build
LDFLAGS=${LDFLAGS/\$/} cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${TARGET} \
  -DCMAKE_TOOLCHAIN_FILE=${ROOT}/Toolchain.cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_CODEC=OFF
make install/strip

mkdir ${DEPS}/poppler
$CURL https://poppler.freedesktop.org/poppler-${VERSION_POPPLER}.tar.xz | tar xJC ${DEPS}/poppler --strip-components=1
cd ${DEPS}/poppler
# Disable building pdf-fullrewrite - which fails
sed -i'.bak' '/.*pdf-fullrewrite[ _].*/d' test/CMakeLists.txt
mkdir build
cd build
LDFLAGS=${LDFLAGS/\$/} cmake .. -G"Unix Makefiles" \
  -DCMAKE_TOOLCHAIN_FILE=${ROOT}/Toolchain.cmake -DCMAKE_INSTALL_PREFIX=${TARGET} -DCMAKE_INSTALL_LIBDIR=${TARGET}/lib \
  -DBUILD_GTK_TESTS=OFF -DBUILD_QT5_TESTS=OFF -DBUILD_QT6_TESTS=OFF -DBUILD_CPP_TESTS=OFF -DENABLE_SPLASH=OFF -DENABLE_UTILS=OFF \
  -DENABLE_CPP=OFF -DENABLE_GTK_DOC=OFF -DENABLE_QT5=OFF -DENABLE_QT6=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=release
make install/strip
```

This mostly works, binary artefacts being produced, and I am able to process some pdf files with sharp.

Unfortunately, it fails for some files, with the following error

`nodejs: symbol lookup error: /[...]/node_modules/sharp/build/Release/../../vendor/8.10.5/lib/libvips.so.42: undefined symbol: opj_stream_default_create`

My (limited) understanding is that openjpeg fails to be linked properly into poppler and/or libvips.

Any advice / idea on what I am missing here?

**Comment by lovell** [comment]
Cross-posted at https://github.com/libvips/libvips/issues/1944

**Comment by olivier-lacroix** [comment]
yes indeed @lovell . Since it seems to be a failure of poppler to link in libopenjp2, I have also reported the issue there [there ](https://gitlab.freedesktop.org/poppler/poppler/-/issues/1019)

Any idea or advice to make poppler pull in openjp2 properly by any chance?

**Comment by olivier-lacroix** [comment]
@lovell, I was able to solve this with the help of @kleisauke in https://github.com/libvips/libvips/issues/1944

@jcupitt mentioned that the next version of libvips would have "easy" support for pdfium. @lovell, is this something you would consider including in default binaries?

**Comment by olivier-lacroix** [comment]
For reference, the working patch [here](https://github.com/olivier-lacroix/sharp-libvips/commit/235df0bda2f8805b47493b131e9551bdcbcfd2eb)

**Comment by lovell** [comment]
@olivier-lacroix Please see https://github.com/lovell/sharp/issues/672#issuecomment-517386130

**Comment by olivier-lacroix** [comment]
@lovell . OK thanks.
