### ISSUE TITLE
Downloads of this package have started failing today (ECONNRESET)

### ISSUE THREAD

**Issue by kaiyoma** [lovell/sharp-libvips#83]
Without warning, a lot of our CI builds have failed today with this error (during step 4 of `yarn install`):

```
09:03:30  [4/4] Building fresh packages...
09:03:48  error /home/jenkins/workspace/Geiger/geiger-review/node_modules/sharp: Command failed.
09:03:48  Exit code: 1
09:03:48  Command: (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
09:03:48  Arguments: 
09:03:48  Directory: /home/jenkins/workspace/Geiger/geiger-review/node_modules/sharp
09:03:48  Output:
09:03:48  info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz
09:03:48 
 ERR! sharp read ECONNRESET
```

I realize this is probably a GitHub issue and has nothing to do with your project, but posting here anyway for visibility and posterity.

**Comment by lovell** [comment]
The relative silence suggests this is a temporary problem with networking between your CI environment and either GitHub or AWS S3.

(When there's a real GitHub Releases problem affecting everyone I receive at least 100 notifications, emails, Twitter DMs, carrier pigeons etc.)

**Comment by kaiyoma** [comment]
Okay good to know. Thanks for the info!
