### ISSUE TITLE
Prebuilt libvips 8.10.0 binaries are not yet available for android-armv7

### ISSUE THREAD

**Issue by bilal-08** [lovell/sharp-libvips#85]
this may not sound weird but i wanna download dependencies in android using termux so i can use it portably so Can it be possible?

**Comment by lovell** [comment]
For termux, see https://github.com/lovell/sharp/issues/1889#issuecomment-535840238

**Comment by bilal-08** [comment]
> For termux, see [lovell/sharp#1889 (comment)](https://github.com/lovell/sharp/issues/1889#issuecomment-535840238)

Omg tnx
